### ISSUE TITLE
No configuration information available, and the existing one is out of date.

### ISSUE THREAD

**Issue by SerafimArts** [StyleCI/Docs#21]
It is necessary to add information about setting up the project. The only information about this is in the blog, but there are screens that do not correspond to reality: https://alt-three.com/getting-started-with-styleci-and-github/

## Expected:
![image](https://user-images.githubusercontent.com/2461257/56596341-124fea00-65f9-11e9-8321-472475a78ef9.png)

## Actual: 
![image](https://user-images.githubusercontent.com/2461257/56596588-7e325280-65f9-11e9-8b41-31893338b116.png)

 and there it is **impossible** to choose an OS plan or somehow customize the project settings.

**Comment by GrahamCampbell** [comment]
For support queries, please contact support@styleci.io or use the support contact form on the website.
