### ISSUE TITLE
Documentation does not contain information about account setup

### ISSUE THREAD

**Issue by SerafimArts** [StyleCI/Docs#22]
I will repeat my question (https://github.com/StyleCI/Docs/issues/21) about "Setup Account" step, because support@styleci.io is not responding for the second week (I sent 3 letters and they are all ignored). 

@GrahamCampbell I apologize for this, but I have no other solution to this problem. =\

## Problem

1) There is no "**Setup account**" information in the documentation: https://docs.styleci.io/
2) There is no information about "**We were unable to continue due to duplicate account details**" error in documentation.

## Suggest

Add "setup" documentation page because now it is not clear what to do.

**Comment by GrahamCampbell** [comment]
I don't see any emails on the support system? Could you email again, or perhaps direct email my alt-three.com address with your details? Perhps your emails are being blocked?

**Comment by SerafimArts** [comment]
Done. Message reached:

> Hello,Thank you for getting in touch. You've reached the Alt Three inbox. This is no longer the support inbox for Cachet or StyleCI. We cannot forward Cachet enquiries without your permission due to data protection law. If you are emailing about something else, we'll be in touch shortly.

----

> Perhps your emails are being blocked?

This is the first such case.

----

I can close this issue, but installation information page seems to be quite useful.

**Comment by GrahamCampbell** [comment]
> Done. Message reached, because the answer came:

Please email my personal email graham at alt-three.com. :)
