### ISSUE TITLE
Presets page titles messed up

### ISSUE THREAD

**Issue by GrahamCampbell** [StyleCI/Docs#8]

**Comment by GrahamCampbell** [comment]
Needs html comment adding.

**Comment by GrahamCampbell** [comment]
<img width="299" alt="image" src="https://user-images.githubusercontent.com/2829600/41193719-34bbe710-6c08-11e8-91d7-64ea13ff1f52.png">

**Comment by GrahamCampbell** [comment]
Added comment, but didn't fix layout. // cc @joecohens

**Comment by joecohens** [comment]
Fixed
